# Generated by Django 5.2.4 on 2025-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_book_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=2025),
        ),
    ]
