"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^&8g)+_amz44h@3xg9ff!*2d#!iw)ui&(h1d)-&03*px+5q5hj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf', 
    'relationship_app' 
    'csp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'libraryproject',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '@Lokoja123$'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CustomUser Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'
# REDIRECT AFTER LOGOUT 


# DO NOT keep DEBUG=True in production
DEBUG = False

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Enable the browser’s XSS filter
SECURE_BROWSER_XSS_FILTER = True

# Prevent the browser from guessing content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF and session cookies should only be sent over HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# Protect against XSS and content type guessing
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True


# Optional but recommended
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Optional: Enable HTTPS redirect
SECURE_SSL_REDIRECT = True

# Ensure allowed hosts is set
ALLOWED_HOSTS = ['yourdomain.com', '127.0.0.1', 'localhost']

MIDDLEWARE.insert(0, 'csp.middleware.CSPMiddleware')

# Example CSP configuration:
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", 'cdn.jsdelivr.net')
CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com')
CSP_FONT_SRC = ("'self'", 'fonts.gstatic.com')
CSP_IMG_SRC = ("'self'", 'data:')


# ============================
# HTTPS AND HSTS CONFIGURATION
# ============================

# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True  # 🔒 Redirects all non-HTTPS requests to HTTPS

# HTTP Strict Transport Security: tells browsers to only use HTTPS for the next year
SECURE_HSTS_SECONDS = 31536000  # 🔒 Enforce HTTPS for 1 year (recommended minimum for production)

# Apply HSTS to all subdomains
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 🔒 Includes subdomains in HSTS policy

# Enable preload flag (used by browsers for HSTS preload list)
SECURE_HSTS_PRELOAD = True  # 🔒 Allows HSTS to be preloaded by browsers


# ============================
# SECURE COOKIE CONFIGURATION
# ============================



SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')